env:
  browser: true
  commonjs: true
  es6: true
  jest: true
  node: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'react-app'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react  
settings:
  react:
    version: 'detect'
rules: 
    import/no-unresolved: off
    import/prefer-default-export: off
    import/extensions: off
    react/destructuring-assignment: off
    react/prop-types: off
    react/jsx-filename-extension: off    
    jsx-a11y/anchor-is-valid:
      - warn
      - 
        components:
          - Link
        specialLink:
          - to
          - as
          - hrefLeft
          - hrefRight
        aspects: 
          - invalidHref
          - preferButton
overrides:
  - 
    files: 
      - 'packages/**/*.{ts.tsx}'
    rules: 
      '@typescript-eslint/camelcase': off
      '@typescript-eslint/member-delimiter-style':
        - warn
        -
          multiline:
            delimiter: none
      '@typescript-eslint/explicit-function-return-type':
        - warn
        - 
          allowTypedFunctionExpressions: true
      '@typescript-eslint/interface-name-prefix': 
        - warn
        -
          prefixWithI: never