trailingComma: "es5"
tabWidth: 2
useTabs: false
noSemi: false
singleQuote: true
jsxSingleQuote: true
jsxBracketSameLine: true
arrowParens: "always"
printWidth: 120
bracketSpacing: true
endOfLine: "lf"