// Viewstate
export const VIEWSTATE_SET = 'VIEWSTATE_SET'
export const VIEWSTATE_REMOVE = 'VIEWSTATE_REMOVE'

// Cart
export const CART_FETCH = 'CART_FETCH'
export const CART_RECEIVE = 'CART_RECEIVE'
export const CART_ADD = 'CART_ADD'
export const CART_UPDATE = 'CART_UPDATE'
export const CART_REMOVE = 'CART_REMOVE'

// Products
export const PRODUCTS_FETCH = 'PRODUCTS_FETCH'
export const PRODUCT_FETCH = 'PRODUCT_FETCH'

export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE'
export const PRODUCT_RECEIVE = 'PRODUCT_RECEIVE'

// Pages
export const PAGE_FETCH = 'PAGE_FETCH'
export const PAGE_RECEIVE = 'PAGE_RECEIVE'

// Request
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'
export const REQUEST_LOADING = 'REQUEST_LOADING'

// Search
export const SEARCH_FETCH = 'SEARCH_FETCH'
export const SEARCH_RECEIVE = 'SEARCH_RECEIVE'

export const QUICK_SEARCH_TOGGLE = 'QUICK_SEARCH_TOGGLE'
